nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    # homepage: https://goreleaser.com
    description: |-
      Deliver Go binaries as fast and easily as possible.
      GoReleaser allows you to release easily build, package, publish and
      announce to several places at one go.
    maintainer: Carlos Alexandro Becker <carlos@becker.software>
    license: MIT
    vendor: GoReleaser
    bindir: /usr/bin
    # section: utils
    contents:
      # - src: ./completions/goreleaser.bash
      #   dst: /usr/share/bash-completion/completions/goreleaser
      #   file_info:
      #     mode: 0644
      # - src: ./completions/goreleaser.fish
      #   dst: /usr/share/fish/vendor_completions.d/goreleaser.fish
      #   file_info:
      #     mode: 0644
      # - src: ./completions/goreleaser.zsh
      #   dst: /usr/share/zsh/vendor-completions/_goreleaser
      #   file_info:
      #     mode: 0644
      # - src: ./manpages/goreleaser.1.gz
      #   dst: /usr/share/man/man1/goreleaser.1.gz
      #   file_info:
      #     mode: 0644
      # - src: ./LICENSE.md
      #   dst: /usr/share/doc/goreleaser/copyright
      #   file_info:
      #     mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    recommends:
      - golang -nala
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
