name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'  
      - name: Install dependencies
        run: |
          go install github.com/rakyll/gotest@latest 
          go install github.com/goreleaser/goreleaser

      - name: Build
        run: go build -v ./...

      - name: Install
        run: go install -x ./...

      - name: Test
        run: gotest -v ./...

      - name: Release
        run: goreleaser --snapshot --clean

