name: Themes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Themes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          go install github.com/rakyll/gotest@latest 
          go install github.com/goreleaser/goreleaser@latest

      - name: Build
        run: go build -v ./...

      - name: Install
        run: go install -x ./...

      - name: Test
        run: gotest -v ./...

      - name: Release
        run: goreleaser --snapshot --clean

